# Generated by Django 4.2.20 on 2025-04-23 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeIngredientModel', to='recipes.ingredientmodel', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='tags',
            field=models.ManyToManyField(to='recipes.tagmodel', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='recipeingredientmodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientmodel', verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipeingredientmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingredientmodel',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='Unique Ingredient-measurement_unit constraint'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredientmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Unique recipe-ingredient constraint'),
        ),
    ]
