# Generated by Django 4.2.20 on 2025-04-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredientmodel_recipeingredientmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'default_related_name': 'recipes', 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
