# Generated by Django 4.2.20 on 2025-05-11 08:03

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipemodel_options_recipemodel_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='short_link',
            field=models.CharField(default=recipes.models.get_uuid, editable=False, max_length=7, unique=True),
        ),
    ]
