# Generated by Django 4.2.20 on 2025-04-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientmodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientmodel', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipeingredientmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel', verbose_name='Рецепт'),
        ),
    ]
