# Generated by Django 4.2.20 on 2025-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredientmodel_ingredient_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredientmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Unique recipe-ingredient constraint', violation_error_message=('Ингредиент уже есть в рецепте.',)),
        ),
    ]
