# Generated by Django 4.2.20 on 2025-04-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeingredientmodel_unique_recipe_ingredient_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredientmodel',
            name='Unique recipe-ingredient constraint',
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='tags',
            field=models.ManyToManyField(to='recipes.tagmodel', verbose_name='Тег'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredientmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='Unique recipe-ingredient constraint'),
        ),
    ]
