# Generated by Django 4.2.20 on 2025-04-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipeingredientmodel_unique_recipe_ingredient_constraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientmodel',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='Unique Ingredient-measurement_unit constraint'),
        ),
    ]
