# Generated by Django 4.2.20 on 2025-04-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientmodel_unique_ingredient_measurement_unit_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientmodel',
            options={'ordering': ('name',), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'default_related_name': 'recipes', 'ordering': ('name',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'ordering': ('name',), 'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
