# Generated by Django 4.2.20 on 2025-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribemodel',
            name='user_and_target_different',
        ),
        migrations.RemoveConstraint(
            model_name='subscribemodel',
            name='Unique user-target constraint',
        ),
        migrations.AddConstraint(
            model_name='subscribemodel',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('target')), _negated=True), name='user_and_target_different', violation_error_message='Нельзя подписаться на себя.'),
        ),
        migrations.AddConstraint(
            model_name='subscribemodel',
            constraint=models.UniqueConstraint(fields=('user', 'target'), name='Unique user-target constraint', violation_error_message='На этого пользователя вы уже подписаны.'),
        ),
    ]
