# Generated by Django 4.2.20 on 2025-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_subscribemodel_user_and_target_different_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribemodel',
            name='Unique user-target constraint',
        ),
        migrations.AddConstraint(
            model_name='subscribemodel',
            constraint=models.UniqueConstraint(fields=('user', 'target'), name='Unique user-target constraint'),
        ),
    ]
