# Generated by Django 4.2.20 on 2025-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_foodgramuser_avatar_alter_foodgramuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/'),
        ),
    ]
