# Generated by Django 4.2.20 on 2025-04-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcartmodel',
            name='Unique ShoppingCart constraint',
        ),
        migrations.RenameField(
            model_name='shoppingcartmodel',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='shoppingcartmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Unique ShoppingCart constraint'),
        ),
    ]
