# Generated by Django 4.2.20 on 2025-04-23 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorite_cart', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='favoritecartmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favoritecartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Unique recipe_user constraint, favorite_cart_shoppingcartmodel'),
        ),
        migrations.AddConstraint(
            model_name='favoritecartmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Unique recipe_user constraint, favorite_cart_favoritecartmodel'),
        ),
    ]
