# Generated by Django 4.2.20 on 2025-04-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecartmodel',
            options={'verbose_name': 'избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartmodel',
            options={'verbose_name': 'список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
