# Generated by Django 4.2.20 on 2025-05-06 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
        ('favorite_cart', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteCartModel',
            new_name='FavoriteModel',
        ),
        migrations.RemoveConstraint(
            model_name='favoritemodel',
            name='Unique recipe_user constraint, favorite_cart_favoritecartmodel',
        ),
        migrations.AddConstraint(
            model_name='favoritemodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Unique recipe_user constraint, favorite_cart_favoritemodel'),
        ),
    ]
