# Generated by Django 4.2.20 on 2025-04-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_cart', '0004_alter_favoritecartmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecartmodel',
            options={'default_related_name': 'favorites_carts', 'verbose_name': 'избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartmodel',
            options={'default_related_name': 'shoppings_carts', 'verbose_name': 'список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
